language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn lint
  - yarn build
deploy:
  edge: true
  provider: firebase
  project: $FIREBASE_PROJECT
  token:
    secure: $FIREBASE_TOKEN
